# default configuration
baseURL = "http://proaplicaciones.com"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Proaplicaciones: Productividad y Aplicaciones"

# css plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"


# menu
[[menu.main]]
URL = "about"
name = "Acerca de Nosotros"
weight = 2

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3

#[[menu.main]]
#URL = "portfolio"
#name = "Portfolio"
#weight = 4

[[menu.main]]
URL = "contact"
name = "Contáctenos"
weight = 5


# default parameters
[params]
home = "Home"
logo = "images/logo.svg"
# theme color
theme_color = "#41228e"
# contact info
phone = "+57 312-496-8693 / +57 300-305-7003"
email = "felipe@proaplicaciones.com"
address = "Bogotá, Colombia"
# meta description
author = "Luis Felipe Valdés"
description = "empresa de desarrollo de software en bogota"
# google analytics
google_analytics_id = "UA-75484739-1" # Proaplicaciones Todos los datos de sitios web
# copyright
copyright = "Copyright &copy; 2013-2020  Todos los derechos reservados"


# contact
[params.contact]
enable = true
form_action = "#" # contact form works with : https://formspree.io

# preloader
[params.preloader]
enable = true
preloader = "" # use png, jpg, svg or gif format

# social site
[[params.social]]
URL = "#"
icon = "ti-facebook"

[[params.social]]
URL = "#"
icon = "ti-instagram"

#[[params.social]]
#URL = "#"
#icon = "ti-dribbble"

[[params.social]]
URL = "#"
icon = "ti-twitter-alt"
